[[05/11/2025 08:51:24 AM]] 
new run with parameters:
{'attention_mixture_components': 10,
 'batch_size': 32,
 'batch_sizes': [32],
 'beta1_decay': 0.9,
 'beta1_decays': [0.9],
 'checkpoint_dir': 'checkpoints_style_synthesis',
 'early_stopping_steps': 2000,
 'enable_parameter_averaging': False,
 'grad_clip': 10,
 'keep_prob_scalar': 1.0,
 'learning_rate': 0.0001,
 'learning_rates': [0.0001],
 'log_dir': 'logs_style_synthesis',
 'log_interval': 50,
 'logging_level': 20,
 'loss_averaging_window': 100,
 'lstm_size': 400,
 'min_steps_to_checkpoint': 2000,
 'num_restarts': 0,
 'num_training_steps': 30000,
 'optimizer': 'rms',
 'output_mixture_components': 20,
 'output_units': 121,
 'patiences': [2000],
 'prediction_dir': 'predictions_style_synthesis',
 'reader': None,
 'regularization_constant': 0.0,
 'restart_idx': 0,
 'style_embedding_size': 256,
 'validation_batch_size': 32,
 'warm_start_init_step': 0}
[[05/11/2025 08:51:27 AM]] all parameters:
[[05/11/2025 08:51:27 AM]] [('Variable:0', []),
 ('Variable_1:0', []),
 ('Variable_2:0', []),
 ('style_encoder/bidirectional/lstm_cell/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias:0', [512]),
 ('style_encoder/dense/kernel:0', [256, 1]),
 ('style_encoder/dense/bias:0', [1]),
 ('style_encoder/dense_1/kernel:0', [256, 256]),
 ('style_encoder/dense_1/bias:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel:0', [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights:0', [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn_style/gmm/weights:0', [400, 121]),
 ('rnn_style/gmm/biases:0', [121]),
 ('style_encoder/bidirectional/lstm_cell/kernel/RMSProp:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/kernel/RMSProp_1:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel/RMSProp:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel/RMSProp_1:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias/RMSProp:0', [512]),
 ('style_encoder/bidirectional/lstm_cell/bias/RMSProp_1:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel/RMSProp:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel/RMSProp_1:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel/RMSProp:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel/RMSProp_1:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias/RMSProp:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias/RMSProp_1:0', [512]),
 ('style_encoder/dense/kernel/RMSProp:0', [256, 1]),
 ('style_encoder/dense/kernel/RMSProp_1:0', [256, 1]),
 ('style_encoder/dense/bias/RMSProp:0', [1]),
 ('style_encoder/dense/bias/RMSProp_1:0', [1]),
 ('style_encoder/dense_1/kernel/RMSProp:0', [256, 256]),
 ('style_encoder/dense_1/kernel/RMSProp_1:0', [256, 256]),
 ('style_encoder/dense_1/bias/RMSProp:0', [256]),
 ('style_encoder/dense_1/bias/RMSProp_1:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel/RMSProp:0',
  [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel/RMSProp_1:0',
  [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias/RMSProp:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights/RMSProp:0',
  [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights/RMSProp_1:0',
  [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases/RMSProp:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases/RMSProp_1:0',
  [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel/RMSProp:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel/RMSProp_1:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias/RMSProp:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel/RMSProp:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel/RMSProp_1:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias/RMSProp:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/gmm/weights/RMSProp:0', [400, 121]),
 ('rnn_style/gmm/weights/RMSProp_1:0', [400, 121]),
 ('rnn_style/gmm/biases/RMSProp:0', [121]),
 ('rnn_style/gmm/biases/RMSProp_1:0', [121])]
[[05/11/2025 08:51:27 AM]] trainable parameters:
[[05/11/2025 08:51:27 AM]] [('style_encoder/bidirectional/lstm_cell/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias:0', [512]),
 ('style_encoder/dense/kernel:0', [256, 1]),
 ('style_encoder/dense/bias:0', [1]),
 ('style_encoder/dense_1/kernel:0', [256, 256]),
 ('style_encoder/dense_1/bias:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel:0', [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights:0', [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn_style/gmm/weights:0', [400, 121]),
 ('rnn_style/gmm/biases:0', [121])]
[[05/11/2025 08:51:27 AM]] trainable parameter count:
[[05/11/2025 08:51:27 AM]] 5070128
[[05/11/2025 08:51:27 AM]] built graph
[[05/11/2025 08:51:27 AM]] Restoring parameters from final_checkpoints/model-10350
[[05/11/2025 08:51:27 AM]] Started server process [7]
[[05/11/2025 08:51:27 AM]] Waiting for application startup.
[[05/11/2025 08:51:27 AM]] Application startup complete.
[[05/11/2025 08:51:32 AM]] 
new run with parameters:
{'attention_mixture_components': 10,
 'batch_size': 32,
 'batch_sizes': [32],
 'beta1_decay': 0.9,
 'beta1_decays': [0.9],
 'checkpoint_dir': 'checkpoints_style_synthesis',
 'early_stopping_steps': 2000,
 'enable_parameter_averaging': False,
 'grad_clip': 10,
 'keep_prob_scalar': 1.0,
 'learning_rate': 0.0001,
 'learning_rates': [0.0001],
 'log_dir': 'logs_style_synthesis',
 'log_interval': 50,
 'logging_level': 20,
 'loss_averaging_window': 100,
 'lstm_size': 400,
 'min_steps_to_checkpoint': 2000,
 'num_restarts': 0,
 'num_training_steps': 30000,
 'optimizer': 'rms',
 'output_mixture_components': 20,
 'output_units': 121,
 'patiences': [2000],
 'prediction_dir': 'predictions_style_synthesis',
 'reader': None,
 'regularization_constant': 0.0,
 'restart_idx': 0,
 'style_embedding_size': 256,
 'validation_batch_size': 32,
 'warm_start_init_step': 0}
[[05/11/2025 08:51:34 AM]] all parameters:
[[05/11/2025 08:51:34 AM]] [('Variable:0', []),
 ('Variable_1:0', []),
 ('Variable_2:0', []),
 ('style_encoder/bidirectional/lstm_cell/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias:0', [512]),
 ('style_encoder/dense/kernel:0', [256, 1]),
 ('style_encoder/dense/bias:0', [1]),
 ('style_encoder/dense_1/kernel:0', [256, 256]),
 ('style_encoder/dense_1/bias:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel:0', [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights:0', [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn_style/gmm/weights:0', [400, 121]),
 ('rnn_style/gmm/biases:0', [121]),
 ('style_encoder/bidirectional/lstm_cell/kernel/RMSProp:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/kernel/RMSProp_1:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel/RMSProp:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel/RMSProp_1:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias/RMSProp:0', [512]),
 ('style_encoder/bidirectional/lstm_cell/bias/RMSProp_1:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel/RMSProp:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel/RMSProp_1:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel/RMSProp:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel/RMSProp_1:0',
  [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias/RMSProp:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias/RMSProp_1:0', [512]),
 ('style_encoder/dense/kernel/RMSProp:0', [256, 1]),
 ('style_encoder/dense/kernel/RMSProp_1:0', [256, 1]),
 ('style_encoder/dense/bias/RMSProp:0', [1]),
 ('style_encoder/dense/bias/RMSProp_1:0', [1]),
 ('style_encoder/dense_1/kernel/RMSProp:0', [256, 256]),
 ('style_encoder/dense_1/kernel/RMSProp_1:0', [256, 256]),
 ('style_encoder/dense_1/bias/RMSProp:0', [256]),
 ('style_encoder/dense_1/bias/RMSProp_1:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel/RMSProp:0',
  [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel/RMSProp_1:0',
  [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias/RMSProp:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights/RMSProp:0',
  [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights/RMSProp_1:0',
  [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases/RMSProp:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases/RMSProp_1:0',
  [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel/RMSProp:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel/RMSProp_1:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias/RMSProp:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel/RMSProp:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel/RMSProp_1:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias/RMSProp:0',
  [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias/RMSProp_1:0',
  [1600]),
 ('rnn_style/gmm/weights/RMSProp:0', [400, 121]),
 ('rnn_style/gmm/weights/RMSProp_1:0', [400, 121]),
 ('rnn_style/gmm/biases/RMSProp:0', [121]),
 ('rnn_style/gmm/biases/RMSProp_1:0', [121])]
[[05/11/2025 08:51:34 AM]] trainable parameters:
[[05/11/2025 08:51:34 AM]] [('style_encoder/bidirectional/lstm_cell/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell/bias:0', [512]),
 ('style_encoder/bidirectional/lstm_cell_1/kernel:0', [3, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/recurrent_kernel:0', [128, 512]),
 ('style_encoder/bidirectional/lstm_cell_1/bias:0', [512]),
 ('style_encoder/dense/kernel:0', [256, 1]),
 ('style_encoder/dense/bias:0', [1]),
 ('style_encoder/dense_1/kernel:0', [256, 256]),
 ('style_encoder/dense_1/bias:0', [256]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/kernel:0', [732, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/weights:0', [732, 30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/attention/biases:0', [30]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/kernel:0',
  [1132, 1600]),
 ('rnn_style/StyleAdaptiveLSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn_style/gmm/weights:0', [400, 121]),
 ('rnn_style/gmm/biases:0', [121])]
[[05/11/2025 08:51:34 AM]] trainable parameter count:
[[05/11/2025 08:51:34 AM]] 5070128
[[05/11/2025 08:51:34 AM]] built graph
[[05/11/2025 08:51:34 AM]] Restoring parameters from final_checkpoints/model-10350
[[05/11/2025 08:51:35 AM]] Model initialized successfully
[[05/11/2025 09:09:42 AM]] Saved request data to saved_requests/request_20250511_090942_dd02040b.json
[[05/11/2025 09:09:42 AM]] Using 16 worker threads with 32 CPU cores
[[05/11/2025 09:09:42 AM]] Processing failed for item 0: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 4: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 1: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 2: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 6: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 7: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 8: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 3: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 5: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 9: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 10: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 12: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 346, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray, style_encoder/bidirectional/TensorArrayStack/range, style_encoder/bidirectional/while/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 11: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:09:42 AM]] Processing failed for item 13: TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

Caused by op 'style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3', defined at:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 78, in initialize_model
    style_embedding_size=256
  File "./train.py", line 56, in __init__
    super(StyleSynthesisModel, self).__init__(reader=None, **kwargs)
  File "./tf_base_model.py", line 110, in __init__
    self.graph = self.build_graph()
  File "./tf_base_model.py", line 401, in build_graph
    self.loss = self.calculate_loss()
  File "./train.py", line 81, in calculate_loss
    style_emb = style_encoder(self.ref_x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "./train.py", line 26, in call
    x = self.bi_rnn(stroke_sequence)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/wrappers.py", line 347, in call
    y_rev = self.backward_layer.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 2056, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/recurrent.py", line 613, in call
    input_length=timesteps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2963, in rnn
    outputs = output_ta.stack()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 893, in stack
    return self._implementation.stack(name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 291, in stack
    return self.gather(math_ops.range(0, self.size()), name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 305, in gather
    element_shape=element_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4186, in _tensor_array_gather_v3
    flow_in=flow_in, dtype=dtype, element_shape=element_shape, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape [?,128] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: style_encoder/bidirectional/TensorArrayStack_1/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@style_encoder/bidirectional/TensorArray_2"], dtype=DT_FLOAT, element_shape=[?,128], _device="/job:localhost/replica:0/task:0/device:CPU:0"](style_encoder/bidirectional/TensorArray_2, style_encoder/bidirectional/TensorArrayStack_1/range, style_encoder/bidirectional/while_1/Exit_1)]]

[[05/11/2025 09:10:05 AM]] Shutting down
[[05/11/2025 09:10:05 AM]] Waiting for application shutdown.
[[05/11/2025 09:10:05 AM]] Application shutdown complete.
[[05/11/2025 09:10:05 AM]] Finished server process [7]
